# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-02-01 11:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acimage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_title', models.CharField(default='', max_length=20, verbose_name='图片标题')),
                ('image_detail', models.CharField(default='', max_length=200, verbose_name='图片简介')),
                ('image_path', models.ImageField(default='', upload_to='upload/image/%Y/%m', verbose_name='图片路径')),
            ],
            options={
                'verbose_name': '网站相册',
                'verbose_name_plural': '网站相册',
            },
        ),
        migrations.CreateModel(
            name='ImageCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(default='', max_length=20, verbose_name='分类名称')),
                ('category_detail', models.CharField(default='', max_length=100, verbose_name='分类介绍')),
                ('category_icon', models.CharField(default='', max_length=100, verbose_name='分类图标')),
                ('category_sort_id', models.IntegerField(default=1, verbose_name='分类排序')),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='article_image',
            field=models.ImageField(default='', upload_to='upload/image/article/%Y/%m', verbose_name='文章配图'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_type',
            field=models.CharField(choices=[('0', '草稿'), ('1', '软删除'), ('2', '正常')], default='2', max_length=10, verbose_name='文章类别'),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='site_logo',
            field=models.ImageField(default='', upload_to='upload/image/site/', verbose_name='站点logo'),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='site_topimage',
            field=models.ImageField(default='', upload_to='upload/image/site/', verbose_name='顶部大图'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_detail',
            field=models.CharField(default='', max_length=200, verbose_name='人简介'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_image',
            field=models.ImageField(default='', upload_to='upload/image/user/%Y/%m', verbose_name='用户头像'),
        ),
        migrations.AddField(
            model_name='acimage',
            name='image_category',
            field=models.ForeignKey(default=1, max_length=20, on_delete=django.db.models.deletion.CASCADE, to='blog.ImageCategory', verbose_name='图片分类'),
        ),
    ]
