# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-02-01 21:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190201_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='acimage',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='acimage',
            name='time_modify',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
    ]
