# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-02-01 21:38
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190201_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_like',
            field=models.IntegerField(default=0, verbose_name='点赞数'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_content',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='', verbose_name='博客正文'),
        ),
    ]
