# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-03-16 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190201_2329'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': '文章', 'verbose_name_plural': '文章'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
        migrations.AlterField(
            model_name='article',
            name='article_image',
            field=models.ImageField(default='', null=True, upload_to='upload/image/article/%Y/%m', verbose_name='文章配图'),
        ),
    ]
