# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-03-16 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20190316_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='upload/image/article/%Y/%m', verbose_name='文章配图'),
        ),
    ]
