# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-10-12 01:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20190316_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_click',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='文章点击量'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_create_time',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_type',
            field=models.CharField(choices=[('0', '草稿'), ('1', '软删除'), ('2', '正常')], db_index=True, default='2', max_length=10, verbose_name='文章类别'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_sort_id',
            field=models.IntegerField(db_index=True, default=1, verbose_name='分类排序'),
        ),
    ]
