# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-01-03 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20191012_0136'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_ua', models.CharField(default='', max_length=512)),
                ('request_ip', models.GenericIPAddressField(default='')),
                ('request_region', models.CharField(default='', max_length=128)),
                ('request_times', models.IntegerField(default=0)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_modify', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '访客信息',
                'verbose_name_plural': '访客信息',
            },
        ),
    ]
