# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-01-03 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20200103_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestinfo',
            name='request_times',
            field=models.IntegerField(default=0),
        ),
    ]
