# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-01-06 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20200103_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestinfo',
            name='request_referer',
            field=models.CharField(default='', max_length=512),
        ),
    ]
