# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-01-07 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_requestinfo_request_referer'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestinfo',
            name='request_path',
            field=models.CharField(default='', max_length=512),
        ),
    ]
