# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-05-29 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20200529_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestinfo',
            name='request_referer',
            field=models.CharField(default='', max_length=2048),
        ),
    ]
