# coding=utf-8
"""
Django settings for MyBlog project.

Generated by 'django-admin startproject' using Django 1.11.3.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""
import logging
import os
import socket

import constants
from MyBlog.env import env, env_bool, env_list, load_env

load_env()

hostname = socket.gethostname()
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY', 'change-me')

# SECURITY WARNING: don't run with debug turned on in production!

DEBUG = env_bool('DEBUG', constants.DEBUG)
ALLOWED_HOSTS = env_list('ALLOWED_HOSTS', ['127.0.0.1', 'localhost'])


def env_int(name, default):
    try:
        return int(env(name, default))
    except (TypeError, ValueError):
        return default


def env_float(name, default):
    try:
        return float(env(name, default))
    except (TypeError, ValueError):
        return default

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_crontab',
    'haystack',
    'blog',
    'api',
    'ckeditor',
    'ckeditor_uploader',
    'rest_framework',

]

# Haystack  设置 ES
HAYSTACK_CONNECTIONS = {
    'default': {
        'ENGINE': 'haystack.backends.elasticsearch_backend.ElasticsearchSearchEngine',
        'URL': env('HAYSTACK_URL', 'http://127.0.0.1:9200/'),
        'INDEX_NAME': env('HAYSTACK_INDEX_NAME', 'blog'),
    },
}
# 当添加、修改、删除数据时，自动生成索引
HAYSTACK_SIGNAL_PROCESSOR = 'haystack.signals.RealtimeSignalProcessor'

REST_FRAMEWORK = {
    # 异常处理
    "EXCEPTION_HANDLER": "api.exceptions.exception_handler",
    "DEFAULT_PAGINATION_CLASS": 'api.pagination.StandardResultsSetPagination',
}

CRONJOBS = [
    ('0 2 * * *', 'MyBlog.utils.record_visitor', '>> /data/logs/blog_crontab.log 2>&1'),
    ('0 3 * * *', 'MyBlog.utils.record_ip', '>> /data/logs/blog_crontab.log 2>&1'),
    ('43 6 * * *', 'MyBlog.cron.push_baidu_urls_daily', '>> /data/logs/blog_baidu_push.log 2>&1'),
]

if env_bool('TECH_NEWS_CRON_ENABLED', False):
    CRONJOBS.append(
        ('23 6 * * *', 'MyBlog.cron.import_tech_news_daily', '>> /data/logs/blog_tech_news.log 2>&1')
    )

AUTH_USER_MODEL = 'blog.UserProfile'

MIDDLEWARE = [

    'django.middleware.security.SecurityMiddleware',
    'blog.middleware.CanonicalHostRedirectMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'blog.middleware.OnlineMiddleware'
]

ROOT_URLCONF = 'MyBlog.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],  # 设置网站模板根目录
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # 上下文Context定义
                'MyBlog.context_processor.site_info',

            ],
        },
    },
]

WSGI_APPLICATION = 'MyBlog.wsgi.application'

EMAIL_BACKEND = env('EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = env('EMAIL_HOST', '')
EMAIL_PORT = env_int('EMAIL_PORT', 25)
EMAIL_HOST_USER = env('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD', '')
EMAIL_USE_SSL = env_bool('EMAIL_USE_SSL', False)
EMAIL_USE_TLS = env_bool('EMAIL_USE_TLS', False)
EMAIL_TIMEOUT = env_int('EMAIL_TIMEOUT_SECONDS', 8)
DEFAULT_FROM_EMAIL = env('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER)

SITE_ASSISTANT_MODE = env('SITE_ASSISTANT_MODE', 'rules')
LOCAL_LLM_BASE_URL = env('LOCAL_LLM_BASE_URL', '')
LOCAL_LLM_BASE_URLS = env_list('LOCAL_LLM_BASE_URLS', [])
LOCAL_LLM_API_KEY = env('LOCAL_LLM_API_KEY', '')
LOCAL_LLM_MODEL = env('LOCAL_LLM_MODEL', '')
LOCAL_LLM_TIMEOUT_SECONDS = env_float('LOCAL_LLM_TIMEOUT_SECONDS', 4)
LOCAL_LLM_MAX_NEW_TOKENS = env_int('LOCAL_LLM_MAX_NEW_TOKENS', 220)
LOCAL_LLM_TEMPERATURE = env_float('LOCAL_LLM_TEMPERATURE', 0.4)

# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': env('MYSQL_DATABASE', 'blog'),
        'USER': env('MYSQL_USER', 'blog'),
        'PASSWORD': env('MYSQL_PASSWORD', ''),
        'HOST': env('MYSQL_HOST', '127.0.0.1'),
        'PORT': env('MYSQL_PORT', '3306'),
        'CONN_MAX_AGE': constants.MASTER_DATABASE_CONN_MAX_AGE,
        'OPTIONS': {
            'charset': 'utf8mb4',
            'init_command': 'SET NAMES utf8mb4',
        },
    }
}

# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/
# 修改时区时间设置
LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

# 静态文件
# STATIC_URL = '/static/'


# MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# MEDIA_ROOT = 'media'

# 七牛云密钥等配置
QINIU_ACCESS_KEY = env('QINIU_ACCESS_KEY', '')
QINIU_SECRET_KEY = env('QINIU_SECRET_KEY', '')
QINIU_BUCKET_NAME = env('QINIU_BUCKET_NAME', '')
QINIU_BUCKET_DOMAIN = env('QINIU_BUCKET_DOMAIN', '')
QINIU_SECURE_URL = env_bool('QINIU_SECURE_URL', True)


def build_qiniu_base_url():
    domain = QINIU_BUCKET_DOMAIN.strip().rstrip('/')
    if not domain:
        return ''
    if domain.startswith(('http://', 'https://')):
        return domain
    scheme = 'https' if QINIU_SECURE_URL else 'http'
    return '{}://{}'.format(scheme, domain)


PREFIX_URL = build_qiniu_base_url()
QINIU_ENABLED = bool(QINIU_ACCESS_KEY and QINIU_SECRET_KEY and QINIU_BUCKET_NAME and PREFIX_URL)

if QINIU_ENABLED:
    DEFAULT_FILE_STORAGE = 'qiniustorage.backends.QiniuStorage'
    STATICFILES_STORAGE = 'qiniustorage.backends.QiniuStaticStorage'

STATIC_URL = PREFIX_URL + '/static/' if QINIU_ENABLED else '/static/'

# 上传文件地址配置
MEDIA_URL = PREFIX_URL + '/' if QINIU_ENABLED else '/media/'
STATIC_ROOT = env('QINIU_STATIC_PREFIX', 'static') if QINIU_ENABLED else env('STATIC_ROOT', os.path.join(BASE_DIR, 'staticfiles'))
MEDIA_ROOT = env('MEDIA_ROOT', os.path.join(BASE_DIR, 'media'))

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "cdn"),
]

# STATIC_ROOT = 'static'
# print(STATIC_ROOT, STATIC_URL)
CKEDITOR_UPLOAD_PATH = 'upload/image/'

CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'full',
        'toolbar_Custom': [['Blockquote', 'CodeSnippet'], ],
        'extraPlugins': ','.join(['codesnippet', 'uploadimage', 'widget', 'lineutils', ]),
        'height': 800,
        'width': 900
    },
}


def ensure_parent_dir(path):
    parent = os.path.dirname(path)
    if not parent or os.path.exists(parent):
        return
    try:
        os.makedirs(parent)
    except OSError:
        if not os.path.exists(parent):
            raise


ensure_parent_dir(constants.LOG_FILE_PATH)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'standard': {
            'format': '%(asctime)s [pid:%(process)d] [%(levelname)s] %(message)s'
        },
        'precise': {
            'format': '[pid:%(process)d]  %(levelname)s \x1b[6;30;42m%(asctime)s\x1b[0m %(name)s \x1b[1;32;40m%(message)s\x1b[0m\n'
        },
    },
    'handlers': {
        'default': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': constants.LOG_FILE_PATH,  # 日志输出文件
            'maxBytes': constants.LOG_MAX_BYTES,  # 备份大小
            'backupCount': constants.LOG_BACKUP_COUNT,  # 备份份数
            'formatter': 'precise',  # 使用哪种formatters日志格式
        },
        'error': {
            'level': 'ERROR',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': constants.LOG_FILE_PATH,
            'maxBytes': constants.LOG_MAX_BYTES,
            'backupCount': constants.LOG_BACKUP_COUNT,
            'formatter': 'precise',
        },
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'standard'
        },
        'request_handler': {
            'level': 'DEBUG',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': constants.LOG_FILE_PATH,
            'maxBytes': constants.LOG_MAX_BYTES,
            'backupCount': constants.LOG_BACKUP_COUNT,
            'formatter': 'standard',
        },
        'scprits_handler': {
            'level': 'DEBUG',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': constants.LOG_FILE_PATH,
            'maxBytes': constants.LOG_MAX_BYTES,
            'backupCount': constants.LOG_BACKUP_COUNT,
            'formatter': 'standard',
        }
    },
    'loggers': {
        'django': {
            'handlers': ['console'] if DEBUG else ['default', 'console'],
            'level': 'INFO',
            'propagate': False
        },
        'django.request': {
            'handlers': ['request_handler'],
            'level': 'INFO',
            'propagate': False,
        },
        'scripts': {
            'handlers': ['scprits_handler'],
            'level': 'INFO',
            'propagate': False
        },
        'django.error': {
            'handlers': ['default', 'error'],
            'level': 'ERROR',
            'propagate': True
        }
    }
}

logger = logging.getLogger('django')
